version: "3.1"
services:

    mariadb:
      image: mariadb:10.4
      container_name: phpgrid-mariadb
      working_dir: /application
      volumes:
        - .:/application
        - ./engine/mariadb:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=P@ssw0rd
        - MYSQL_DATABASE=dbname
        - MYSQL_USER=dbusername
        - MYSQL_PASSWORD=dbP@ssw0rd
      ports:  
        - "11302:3306"

    webserver:
      image: nginx:alpine
      container_name: phpgrid-nginx
      working_dir: /application
      volumes:
          - .:/application
          - ./engine/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      ports:
       - "11303:80"

    php-fpm:
      build: engine/php-fpm
      container_name: phpgrid-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./engine/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini:ro
